### ISSUE TITLE
// Clear the existing footer row  tbody.removeChild(tbody.lastChild);

### ISSUE THREAD

**Issue by triciasawyer** [EmmaJohnsonBarth/cookie-stand#14]
https://github.com/EmmaJohnsonBarth/cookie-stand/blob/ddfae433b9623f2d19da4017214d8f8817247118/js/app3.js#L120

**Comment by triciasawyer** [comment]
To get rid of the added footer total after adding a new location, add this line of code:

// Clear the existing footer row
tbody.removeChild(tbody.lastChild);

**Comment by EmmaJohnsonBarth** [comment]
Added! Works!
